# Use this only in dev environments. It's not intended for production usage.
version: '3.9'
services:

  keycloak:
    image: ${KEYCLOAK_IMAGE:-quay.io/keycloak/keycloak:20.0.3}
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '9090:9090'
    command: 'start-dev --http-relative-path /auth --http-port=9090'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/auth/realms/miranum/.well-known/openid-configuration" ]
      interval: 5s
      timeout: 2s
      retries: 30
    env_file:
      - '.env'
    environment:
      KC_HOSTNAME: keycloak # this hostname must be resolved to 127.0.0.1 locally. Add it to your hosts file.
      KC_HOSTNAME_STRICT: 'false'
      KC_DB: ${LOCAL_KEYCLOAK_DB_VENDOR}
      KC_TRANSACTION_XA_ENABLED: 'false'
      KC_DB_URL: ${SSO_DATASOURCE_URL}
      KC_DB_USERNAME: ${SSO_DATASOURCE_USERNAME}
      KC_DB_PASSWORD: ${SSO_DATASOURCE_PASSWORD}
      KEYCLOAK_ADMIN: ${SSO_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${SSO_ADMIN_PASSWORD:-admin}
    networks:
      - local-keycloak
      - internal

  keycloak-init:
    image: klg71/keycloakmigration
    container_name: keycloak-init
    env_file:
      - '.env'
    environment:
      ADMIN_USER: ${SSO_ADMIN:-admin}
      ADMIN_PASSWORD: ${SSO_ADMIN_PASSWORD:-admin}
      BASEURL: http://keycloak:9090/auth
      WAIT_FOR_KEYCLOAK: 'true'
      KEYCLOAK_CHANGELOG: /migration/keycloak-changelog.yml
    volumes:
      - './keycloak:/migration'
    networks:
      - local-keycloak

  postgres:
    image: postgres:15.3
    container_name: postgres
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "su - postgres -c 'psql -l | grep $${SSO_DATASOURCE_DB} | wc -l'" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - '.env'
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${ENGINE_DATASOURCE_DB},${SCHEMA_DATASOURCE_DB},${SSO_DATASOURCE_DB}
      - POSTGRES_PASSWORD=${LOCAL_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${LOCAL_DATASOURCE_USERNAME}
    networks:
      - internal

networks:
  local-keycloak:
  internal:
